# site keywords
keywords = ["Blog", "Coder", "Life"]

# site description
description = "unlease everything, what left"

# Header config
# 页面头部导航栏配置
[header]
  # desktop header mode ("fixed", "normal", "auto")
  # 桌面端导航栏模式 ("fixed", "normal", "auto")
  desktopMode = "fixed"
  # mobile header mode ("fixed", "normal", "auto")
  # 移动端导航栏模式 ("fixed", "normal", "auto")
  mobileMode = "auto"
  # Header title config
  # 页面头部导航栏标题配置
  [header.title]
    # URL of the LOGO
    # LOGO 的 URL
    logo = ""
    # title name
    # 标题名称
    name = "Do It."
    # you can add extra information before the name (HTML format is supported), such as icons
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = "<i class='fas fa-hand-holding-heart fa-fw'></i>"
    # you can add extra information after the name (HTML format is supported), such as icons
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    # whether to use typeit animation for title name
    # 是否为标题显示打字机动画
    typeit = true
    # whether to show RSS icon
    # 是否显示RSS图标
    rss = true

# App icon config
[app]
  # optional site title override for the app when added to an iOS home screen or Android launcher
  title = "Do It."
  # whether to omit favicon resource links
  noFavicon = false
  # modern SVG favicon to use in place of older style .png and .ico files
  svgFavicon = ""
  # Android browser theme color
  themeColor = "#ffffff"
  # Safari mask icon color
  iconColor = "#5bbad5"
  # Windows v8-10 tile color
  tileColor = "#da532c"
# Search config
[search]
  enable = true
  # type of search engine ("lunr", "algolia")
  type = "lunr"
  # max index length of the chunked content
  contentLength = 4000
  # placeholder of the search bar
  placeholder = ""
  # max number of results length
  maxResultLength = 10
  # snippet length of the result
  snippetLength = 30
  # HTML tag name of the highlight part in results
  highlightTag = "em"
  # whether to use the absolute URL based on the baseURL in search index
  absoluteURL = false
  [search.algolia]
    index = "index.en"
    appID = ""
    searchKey = ""

# About page config
[about]
  # whether to enable profile on about page
  # depends on .Site.Params.home.profile.enable
  enable = true
  # whether to enable param layout
  param = true
  # title for param layout
  paramTitle = "Personal Information"
  # general description of your site
  # can be write with markdown style
  description = "Just Do IT."
  # description of your status
  [[about.status]]
    faIcon = "fas fa-building"
    title = "Company"
    desc = "CUPD"
  [[about.status]]
    faIcon = "fas fa-briefcase fa-fw"
    title = "Occupation"
    desc = "Programmer"
  [[about.status]]
    title = "Location"
    faIcon = "fas fa-map-marker-alt"
    desc = "ShangHai"
  # description of your parameter
  [[about.parameter]]
    language = "C"
    level = "80"
  [[about.parameter]]
    language = "Shell"
    level = "80"
  [[about.parameter]]
    language = "Linux"
    level = "80"

# Home page config
[home]
  # amount of RSS pages
  rss = 10
  # Home page profile
  [home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = ""
    # URL of avatar shown in home page
    avatarURL = "/images/avatar.webp"
    # title shown in home page (HTML format is supported)
    title = ""
    # subtitle shown in home page (HTML format is supported)
    subtitle = "temper god gotta be old"
    # whether to use typeit animation for subtitle
    typeit = true
    # whether to show social links
    social = true
    # disclaimer (HTML format is supported)
    disclaimer = ""
  # Home page posts
  [home.posts]
    enable = true
    # special amount of posts in each home posts page
    paginate = 6
    # display image-preview
    imagePreview = true
