# site keywords
keywords = ["Blog", "Coder", "Life"]

# 网站描述
description = "放下所有, 剩下什么"

# Header config
# 页面头部导航栏配置
[header]
  # desktop header mode ("fixed", "normal", "auto")
  # 桌面端导航栏模式 ("fixed", "normal", "auto")
  desktopMode = "fixed"
  # mobile header mode ("fixed", "normal", "auto")
  # 移动端导航栏模式 ("fixed", "normal", "auto")
  mobileMode = "auto"
  # Header title config
  # 页面头部导航栏标题配置
  [header.title]
    # URL of the LOGO
    # LOGO 的 URL
    logo = ""
    # title name
    # 标题名称
    name = "干饭人"
    # you can add extra information before the name (HTML format is supported), such as icons
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = "<i class='fas fa-hand-holding-heart fa-fw'></i>"
    # you can add extra information after the name (HTML format is supported), such as icons
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    # whether to use typeit animation for title name
    # 是否为标题显示打字机动画
    typeit = true
    # whether to show RSS icon
    # 是否显示RSS图标
    rss = true

# 应用图标配置
[app]
  # 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
  title = "干饭人"
  # 是否隐藏网站图标资源链接
  noFavicon = false
  # 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
  svgFavicon = ""
  # Android 浏览器主题色
  themeColor = "#ffffff"
  # Safari 图标颜色
  iconColor = "#5bbad5"
  # Windows v8-10 磁贴颜色
  tileColor = "#da532c"
# 搜索配置
[search]
  enable = true
  # 搜索引擎的类型 ("lunr", "algolia")
  type = "lunr"
  # 文章内容最长索引长度
  contentLength = 4000
  # 搜索框的占位提示语
  placeholder = ""
  # 最大结果数目
  maxResultLength = 10
  # 结果内容片段长度
  snippetLength = 50
  # 搜索结果中高亮部分的 HTML 标签
  highlightTag = "em"
  # 是否在搜索索引中使用基于 baseURL 的绝对路径
  absoluteURL = false
  [search.algolia]
    index = "index.zh-cn"
    appID = ""
    searchKey = ""

# 关于页面配置
[about]
  # 是否启用关于页面的配置文件
  # 依赖于取决于 .Site.Params.home.profile.enable
  enable = true
  # 是否启用参数布局
  param = true
  # 参数布局的标题
  paramTitle = "个人信息"
  # 您网站的一般描述
  # 可以用markdown样式写
  description = "生命在于折腾"
  # 你的状态描述
  [[about.status]]
    faIcon = "fas fa-building"
    title = "公司"
    desc = "CUPD[dispatch]"
  [[about.status]]
    faIcon = "fas fa-briefcase fa-fw"
    title = "职业"
    desc = "程序员"
  [[about.status]]
    title = "地点"
    faIcon = "fas fa-map-marker-alt"
    desc = "上海"
  # 参数说明
  [[about.parameter]]
    language = "C"
    level = "80"
  [[about.parameter]]
    language = "Shell"
    level = "80"
  [[about.parameter]]
    language = "Linux"
    level = "80"

# 主页信息设置
[home]
  # RSS 文章数目
  rss = 10
  # 主页个人信息
  [home.profile]
    enable = true
    # Gravatar 邮箱，用于优先在主页显示的头像
    gravatarEmail = ""
    # 主页显示头像的 URL
    avatarURL = "/images/avatar.webp"
    # 主页显示的网站标题 (支持 HTML 格式)
    title = ""
    # 主页显示的网站副标题 (支持 HTML 格式)
    subtitle = "天若有情"
    # 是否为副标题显示打字机动画
    typeit = true
    # 是否显示社交账号
    social = true
    # 免责声明 (支持 HTML 格式)
    disclaimer = ""
  # 主页文章列表
  [home.posts]
    enable = true
    # 主页每页显示文章数量
    paginate = 6
    # display image-preview
    imagePreview = true
